version: "3.3"

services:
  front:
    container_name: cars-frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  db:
    image: postgres:11-alpine
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: cars-api:v1
    container_name: cars-api
    environment: 
      - PORT=8000
    depends_on:
      - db
    restart: on-failure
    volumes:
      - ./backend/.:/code
    ports:
      - "8000:8000"

volumes:
  dbdata: